Algoritmo "calculo-area-triangulo"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula a área de um triângulo.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 28/03/2026

Var
base, altura, area: real

Inicio
escreva("Digite a base: ")
leia(base)
escreva("Digite a altura: ")
leia(altura)
area <- (base * altura) / 2
escreva("Área do triângulo: ", area)

Fimalgoritmo