Algoritmo "calculo-area-quadrado"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula a área de um quadrado.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 26/03/2026

Var
base, altura, resultado: inteiro

Inicio
escreva("Digite a base do quadrado: ")
leia(base)
escreva("Digite a altura do quadrado: ")
leia(altura)
resultado <- base * altura
escreva("A área do quadrado é:", resultado)

Fimalgoritmo