Algoritmo "calculo-perimetro-quadrado"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula o perímetro de um quadrado.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 26/03/2026

Var
lado, perimetro: real

Inicio
escreva("Digite o valor do lado do quadrado: ")
leia(lado)
perimetro <- lado * 4
escreval("O perímetro do quadrado é: ", perimetro)

Fimalgoritmo