Algoritmo "calculo-area-retangulo"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula a área de um retângulo.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 26/03/2026

Var
base, altura, resultado: inteiro

Inicio
escreva("Digite a base do retângulo: ")
leia(base)
escreva("Digite a altura do retângulo: ")
leia(altura)
resultado <- base * altura
escreva("A área do retângulo é:", resultado)

Fimalgoritmo