Algoritmo "calculo-area-paralelogramo"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula a área de um paralelogramo.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 28/03/2026

Var
base, altura, area: real

Inicio
escreva("Digite a base: ")
leia(base)
escreva("Digite a altura: ")
leia(altura)
area <- base * altura
escreva("Area do paralelogramo: ", area)

Fimalgoritmo
