Algoritmo "celsius-fahrenheit-loop"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Converte graus celsius de 10 até 100 para fahrenheit.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 04/04/2026

Var
c: inteiro
f: real

Inicio

para c de 10 ate 100 passo 10 faca
   f <- (9*c + 160)/5
   escreval(c, "C = ", f, "F")
fimpara

Fimalgoritmo