Algoritmo "comprimento-circunferencia"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula o comprimento de uma circunferência a partir do raio.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 28/03/2026

Var
raio, comprimento: real

Inicio
escreva("Digite o raio do círculo: ")
leia(raio)
comprimento <- 2 * 3.14 * raio
escreval("O comprimento da circunferência é: ", comprimento:5:2)

Fimalgoritmo