Algoritmo "estrutura-repeticao"
// Disciplina   : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exemplo de estrutura de repetição
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 01/04/2026

Var
   contadora: inteiro

Inicio
   enquanto contadora < 5 faça
      escreval("Paulo")
      contadora <- contadora + 1
   fimenquanto

Fimalgoritmo