Algoritmo "estrutura-decisao-composta"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Demonstrar estrutura de decisão composta.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 30/03/2026

Var
numero: inteiro

Inicio 
escreva("Digite um valor: ")
leia (numero)
se numero < 10 entao
  escreval ("O número digitado é menor que 10")
senao
  escreval ("O número é maior que 10")
fimse

Fimalgoritmo