Algoritmo "fahrenheit-celsius"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Converte Fahrenheit para Celsius
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 05/04/2026

Var
F, C: real

Inicio

escreva("Temperatura em Fahrenheit: ")
leia(F)

C <- (F - 32) * (5/9)

escreval("Temperatura em Celsius: ", C)

Fimalgoritmo