Algoritmo "faixa-1-9"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Recebe um número e define se está entre 1 e 9.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 04/04/2026

Var
n: inteiro

Inicio

leia(n)
se n >= 1 e n <= 9 entao
   escreval("Dentro da faixa")
senao
   escreval("Fora da faixa")
fimse

Fimalgoritmo
