Algoritmo "media-tres-valores"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula a média aritmética de três números.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 28/03/2026

Var
n1, n2, n3, media: real

Inicio
escreva("Digite os três números: ")
leia(n1, n2, n3)
media <- (n1 + n2 + n3) / 3
escreval("A média aritmética é: ", media:5:2)

Fimalgoritmo