Algoritmo "metro-para-centimetro"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Converte um valor em metros para centímetros.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 28/03/2026

Var
m, cm: real

Inicio
escreva("Valor em metros: ")
leia(m)
cm <- m * 100
escreval(m, " metros equivalem a ", cm, " centímetros.")

Fimalgoritmo