Algoritmo "multiplicacao"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Realiza a multiplicação entre dois números.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 26/03/2026

Var
numero1, numero2, resultado: inteiro

Inicio
escreva("Digite um número: ")
leia(numero1)
escreva("Digite o segundo número: ")
leia(numero2)
resultado <- numero1 * numero2
escreva("O resultado da multiplicação dos números digitados é:", resultado)

Fimalgoritmo