Algoritmo "potencias-3"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exibe a potencial de 3 do valor digitado.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 04/04/2026

Var
i, valor: inteiro

Inicio

escreva("Digite um valor: ")
leia(valor)
para i de 0 ate 15 faca
   escreval(valor)
   valor <- valor * 3
fimpara

Fimalgoritmo