Algoritmo "quadrado-diferenca"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Lê dois números e imprime o resultado do quadrado da diferença do primeiro valor pelo segundo.ssssss
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 05/04/2026

Var
A, B, resultado: inteiro

Inicio

leia(A, B)

resultado <- (A - B) * (A - B)

escreval("Resultado: ", resultado)

Fimalgoritmo