Algoritmo "soma-quadrados"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Cálcula soma dos lados do quadrado.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 05/04/2026

Var
A, B, C, resultado: real

Inicio

leia(A, B, C)

resultado <- A*A + B*B + C*C

escreval("Resultado: ", resultado)

Fimalgoritmo