Algoritmo "soma"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita dois números para soma e exibe o resultado.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 26/03/2026

Var
numero1, numero2, resultado:inteiro

Inicio
escreva("Digite um número inteiro: ")
leia(numero1)
escreva("Digite o segundo número inteiro: ")
leia(numero2)
resultado <- numero1 + numero2
escreva("A soma dos números digitados é:", resultado)

Fimalgoritmo