Algoritmo "subtracao"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Realiza a subtração entre dois números.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 26/03/2026

Var
numero1: inteiro
numero2: inteiro
resultado: inteiro

Inicio
escreva("Digite um número: ")
leia(numero1)
escreva("Digite o segundo número: ")
leia(numero2)
resultado <- numero1 - numero2
escreva("O resultado da subtração dos números digitados é: ", resultado)

Fimalgoritmo