Algoritmo "metro-para-centimetro"
// Disciplina  : [Logica de Programacao com Visualg]
// Professor   : Jailson Costa dos Santos
// Descricao   : Converte um valor em metros para centimetros.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 28/03/2026

Var
    metro, centimetro: real

Inicio
    escreva("Valor em metros: ")
    leia(metro)

    centimetro <- metro * 100
    escreval(metro, " metros equivalem a ", centimetro, " centimetros.")

Fimalgoritmo