Algoritmo "calculo-perimetro-quadrado"
// Disciplina  : [Logica de Programacao com Visualg]
// Professor   : Jailson Costa dos Santos
// Descricao   : Calcula o perimetro de um quadrado.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 26/03/2026

Var
    lado, perimetro: real

Inicio
    escreva("Digite o valor do lado do quadrado: ")
    leia(lado)

    perimetro <- lado * 4
    escreval("O perimetro do quadrado e: ", perimetro)

Fimalgoritmo