Algoritmo "calculo-area-circulo"
// Disciplina  : [Logica de Programacao com Visualg]
// Professor   : Jailson Costa dos Santos
// Descricao   : Calcula a area de um circulo.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 28/03/2026

Var
    raio, area: real

Inicio
    escreva("Digite o raio: ")
    leia(raio)

    area <- 3.14 * raio * raio
    escreva("Area do circulo: ", area)

Fimalgoritmo