Algoritmo "estrutura-decisao-composta"
// Disciplina  : [Logica de Programacao com Visualg]
// Professor   : Jailson Costa dos Santos
// Descricao   : Demonstrar estrutura de decisao composta.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 30/03/2026

Var
  numero: inteiro

Inicio 
  escreva("Digite um valor: ")
  leia (numero)

  se numero < 10 entao
    escreval ("O numero digitado e menor que 10")
  senao
    escreval ("O numero e maior que 10")
  fimse

Fimalgoritmo