Algoritmo "SejaBemVindo"
// Disciplina  : [Logica de Programacao com Visualg]
// Professor   : Jailson Costa dos Santos
// Descricao   : Exibe uma mensagem de boas-vindas com o nome informado.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 26/03/2026

Var
    nome: caractere

Inicio
    escreva("Digite um nome: ")
    leia(nome)
    escreva("Seja Bem-Vindo (a) ", nome)

Fimalgoritmo