Algoritmo "contagem-regressiva"
// Disciplina  : [Logica de Programacao com Visualg]
// Professor   : Jailson Costa dos Santos
// Descricao   : Exibe uma contagem de 100 ate 0, saltando de 5 em 5.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 17/04/2026

Var
   i: inteiro

Inicio
   escreval("Contagem Regressiva")

   i <- 100
   enquanto i >= 0 faca
      escreval(i)
      i <- i - 5
   fimenquanto

Fimalgoritmo