Algoritmo "estrutura-repeticao"
// Disciplina   : [Logica de Programacao com Visualg]
// Professor   : Jailson Costa dos Santos
// Descricao   : Exemplo de estrutura de repeticao
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 01/04/2026

Var
   contadora: inteiro

Inicio
   enquanto contadora < 5 faca
      escreval("Paulo")
      contadora <- contadora + 1
   fimenquanto

Fimalgoritmo