Algoritmo "soma-quadrados"
// Disciplina  : [Logica de Programacao com Visualg]
// Professor   : Jailson Costa dos Santos
// Descricao   : Calcula soma dos lados do quadrado.
// Autor(a)    : Paulo Henrique Moreira Araujo
// Data atual  : 05/04/2026

Var
    lado, resultado: real

Inicio
    escreval("Digite o valor do lado do quadrado:")
    leia(lado)

    resultado <- lado*4
    escreval("Resultado: ", resultado)

Fimalgoritmo